once upon a time in a forest there lived a monkey who resided on banks of river in the same forest there lived crocodile and his wife...
the kind hearted monkey offered him some fruits. the crocodile came back the next day for more fruits as he loved them
as the days passed by crocodile and monkey became good friends...